### ISSUE TITLE
Docker gives a 'Couldn't connect to Docker daemon' error when not using sudo

### ISSUE THREAD

**Issue by lo9key** [osuosl/iam#111]
The error looks like:

```
lwillmeth@diamond:~/git/iam$ docker-compose run dev bash
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

I suggest adding a few lines to the README.md reminding people to run docker-compose with sudo.

**Comment by alxngyn** [comment]
@lo9key This is an issue with OSL workstations. When I started, some people don't have to use `sudo` but some people (like us) do. Nobody (that I know of) looked into the docker server and why it behaves like that but it's a very OSL specific problem and shouldn't be added to the public README.

**Comment by lo9key** [comment]
Good to know, thank you.
