### ISSUE TITLE
report(fqdn) does not work for plugins

### ISSUE THREAD

**Issue by alxngyn** [osuosl/iam#132]
currently, when passed in a resource=<nodename> 
the current code doesn't work because it doesn't state which field to search in
baseplugin/plugin.rb:
```
      dataset = @@database[@@table].where(resource)
                                   .where(created: start_time..end_time)
```
should be:

```
      dataset = @@database[@@table].where(node: resource)
                                   .where(created: start_time..end_time)
```

**Comment by Kennric** [comment]
Do we not have a test for this method? The plugin tests should include a test that sends an fqdn...

**Comment by alxngyn** [comment]
@Kennric no test
When I revise this, my PR will make a test for this.

**Comment by alxngyn** [comment]
@ElijahCaine Theres a design choice here that I can't really understand. Lets talk about it when you come back to the US.
Ref:
```
def report(resource = {node: '*'},
             start_time = Time.now - (30 * SECONDS_IN_DAY),
             end_time = Time.now)
```

**Comment by ElijahCaine** [comment]
@alxngyn I think we chose to make the resource field a ruby hash so the DB query would work for non-nodes (like databases and FTP servers). If we can preserve that idea it'd make the base plugin very useful going forward as we report data on different types of resources.
