### ISSUE TITLE
Database Resource [8]

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/iam#134]
This will involve a new resource (like nodes) which will gather data and report database usage.
The each resource will have a:
- Name
- Size (kb)
- Server
- Database Type

Database types include:
- PostgreSQL
- MySQL

We will need some sort of database admin user/credentials to get this data. This will not be stored in the code but probably in an environment variable or local (untracked) file.

To review, the resource schema will look something like this:

| id | db_name | db_size | db_server         | db_type |
|----|---------|---------|-------------------|---------|
| 1  | some_db | 1024    | mysql1.osuosl.org | mysql   |

and the plugin entry will look something like this:

| id | name | measurement_table | measurement_units | resource_type | active |
|----|------|-------------------|-------------------|---------------|--------|
| num | db_size | db_resource | kb |  db | true |

**EDIT**
- Added active flag to plugin entry.

**Comment by alxngyn** [comment]
we need an `active` flag like the other plugins

**Comment by ElijahCaine** [comment]
Closed with #141
