### ISSUE TITLE
DB Resource - Data format [3]

### ISSUE THREAD

**Issue by alxngyn** [osuosl/iam#139]
Format the data and put it into the DB to be stored

**Comment by ElijahCaine** [comment]
So we have a query based on the current way we collect statistics:
```ruby
DB.fetch("SELECT table_schema 'DB Name', cast(round(sum( data_length + index_length ) , 1) as binary) 'Data Base Size in Bytes' FROM information_schema.TABLES GROUP BY table_schema") do |e|
  puts e
end
```

Which gives us data that looks like this (run with Sequel on a test database):
```ruby
{:"DB Name"=>"information_schema", :"Data Base Size in Bytes"=>"163840.0"}
{:"DB Name"=>"test_db", :"Data Base Size in Bytes"=>"49152.0"}
```

This is the information we can work with at the moment.

**Comment by alxngyn** [comment]
@ElijahCaine will this data be passed to the cache or a separate object entity?

**Comment by ElijahCaine** [comment]
@alxngyn That data will eventually make it to the cache, however we need to figure out how to group that data by FQDN or project like the nodes are.

**Comment by ElijahCaine** [comment]
@alxngyn Let's make a quick decision on weather or not we want to include this or not. There's an argument to be made for simplicity and an argument to be made for consistency.
I am learning toward the side of simplicity (i.e., close this issue and keep the code he way it is).
