### ISSUE TITLE
Determine testing strategy

### ISSUE THREAD

**Issue by matthewrsj** [osuosl/iam#14]
Testing will be difficult because almost everything is going to be an expensive call to either an API or resource. We need a coherent strategy to make testing useful and (relatively) painless.

**Comment by matthewrsj** [comment]
Something useful found by @Kennric: https://github.com/vcr/vcr

**Comment by ElijahCaine** [comment]
relevant: http://www.sinatrarb.com/testing.html

**Comment by matthewrsj** [comment]
Using spec and factory girl for this.
