### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by alxngyn** [osuosl/iam#142]
## IAM Accounts
- We need a implementation so only approved users can view IAM 
- need for admin accounts to manage other users

### Each account needs(stored into DB or something durable):
1. Username
2. password (sha'd or rainbow table'd)
3. email (if pw is forgotten)
4. Name

### Account needs the forms:
- register(?)
- login
- logout
- forgot pw

### Every page must be handled with:
- A token/cookie that proved authentication
- Token/cookie give user's proper permissions (admin/not admin/not logged in)

**Comment by ElijahCaine** [comment]
What's the purpose of a user? Who will be looking at the pages? If clients are going to use IaM then I agree we need to do this but if it's just single users like a boss then I don't really think we need them.
@Kennric @alxngyn @athai thoughts?

**Comment by alxngyn** [comment]
@ElijahCaine I know we had a couple of conversations for the need of users. I don't remember the why but i remember it was on our todo list.

**Comment by ElijahCaine** [comment]
@Kennric would probably know what our use-case is for users. There's nothing in our design doc about users but of course that doesn't mean we didn't talk about it :smile:

**Comment by ElijahCaine** [comment]
So the plan for this has been to basically host the website behind a simple webserver user/password auth wall (think `.htaccess`).

We should investigate other options but the current audience of the app is ~4 people internal to the OSL so user accounts is looking like overkill.

I'm adding it to a sprint so we can make a *decision* one way or the other.

**Comment by ElijahCaine** [comment]
@Kennric @alxngyn Let's make a decision about user accounts in the next few days.

**Comment by alxngyn** [comment]
I remember we talked about this and said that since there website will be an internal webpage, there is no need for user accounts at the moment.
