### ISSUE TITLE
Improve usability/style of views

### ISSUE THREAD

**Issue by subnomo** [osuosl/iam#144]
Currently we don't have any polished views -- just drafts. We should decide on what we want the views to look like. Keep in mind we are using Bootstrap.

**Comment by alxngyn** [comment]
I vote for Bootstrap as it is simple, big and clear.
For charts I was planning to use this JS library which simplifies D3 graphs
http://metricsgraphicsjs.org/

**Comment by alxngyn** [comment]
I have looked at https://startbootstrap.com/template-overviews/sb-admin-2/
which is a bootstrap admin dashboard that we can repurpose to use for our metrics. 
I'm going to start working on a branch with this unless someone can find something better.
