### ISSUE TITLE
Develop Database Models

### ISSUE THREAD

**Issue by matthewrsj** [osuosl/iam#2]
![notes2241](https://cloud.githubusercontent.com/assets/12090084/13360463/47657448-dc6e-11e5-82f3-dc5b535500bd.jpg)
![notes2242](https://cloud.githubusercontent.com/assets/12090084/13360462/47654acc-dc6e-11e5-827c-3fb5cfae6f64.jpg)

**Comment by matthewrsj** [comment]
![notes2241](https://cloud.githubusercontent.com/assets/12090084/13360463/47657448-dc6e-11e5-82f3-dc5b535500bd.jpg)
![notes2242](https://cloud.githubusercontent.com/assets/12090084/13360462/47654acc-dc6e-11e5-827c-3fb5cfae6f64.jpg)

**Comment by matthewrsj** [comment]
![notes2262](https://cloud.githubusercontent.com/assets/12090084/13366239/f63e6acc-dc8e-11e5-8042-a2e1efec077b.jpg)
![notes2261](https://cloud.githubusercontent.com/assets/12090084/13366240/f64d864c-dc8e-11e5-839b-6c893f3c3c2e.jpg)

**Comment by matthewrsj** [comment]
@mathuin I believe these are largely covered by the draft docs

**Comment by Kennric** [comment]
Closing - initial model design is now in the draft docs.
