### ISSUE TITLE
home page is blank

### ISSUE THREAD

**Issue by alxngyn** [osuosl/iam#218]
current the url `/` is blank
I'll try to add some info on what the project is about and what it is for.
Maybe a "how to use" section

**Comment by Kennric** [comment]
I think a good use of the front page is a summary of the app status:

Short description of what the app is
Number of clients
number of projects
Last collector run for each of the collectors (might have to deduce this from measurement tables)
List of all the things being measured
Maybe total number of each resource measured (total node, total databases, etc)
