### ISSUE TITLE
Collection Status model

### ISSUE THREAD

**Issue by Kennric** [osuosl/iam#221]
It would be useful for several things to have a record of collector runs, and perhaps other stats.

Each model object would consist of a collector name, timestamp, perhaps duration (the collector method should be able to measure run time), maybe total rows in the collected data, a status (failed, succeeded, succeeded with some errors, etc)and anything else that might be useful to capture about collector runs.

**Comment by alxngyn** [comment]
should the model parse the logs or should the collector write a row to the db?
Maybe we can add a feature that parses the logfile in the view and bypass the model?

**Comment by Kennric** [comment]
The collector should write a row to the table on each run, there is no reason to write out to a file and then read back in.
