### ISSUE TITLE
Inconsistent table colors

### ISSUE THREAD

**Issue by hsolorza** [osuosl/iam#238]
With the new bootstrap style, all the tables in IaM should be grey. Though when viewing a client, the tables are white.
![screenshot from 2017-02-10 14 31 29](https://cloud.githubusercontent.com/assets/20174370/22846771/00a1d774-ef9e-11e6-8ed7-a7ce3d1b21e7.png)

**Comment by alxngyn** [comment]
@hsolorza is it just clients? I don't remember adding any client specific CSS

**Comment by hsolorza** [comment]
@alxngyn this seems to only occur with Client and Node.

**Comment by hsolorza** [comment]
@alxngyn  yes, it seems to only occur with the Clients
