### ISSUE TITLE
When disk template is 'plain' nothing is displayed

### ISSUE THREAD

**Issue by ramereth** [osuosl/iam#248]
I noticed when a VM was using the DRBD template, it would display ``Yes``. However, when it's set to plain it's set to nothing. I think a better way to show this is to change the column name to "Disk template" and then just show the name for the template, i.e. "plain" or "drbd".

**Comment by hsolorza** [comment]
I believe this issue will be solved when #241 is merged.

**Comment by ramereth** [comment]
@hsolorza I will check that out when I get a chance. Thank you!
