### ISSUE TITLE
SKU CRUD

### ISSUE THREAD

**Issue by Kennric** [osuosl/iam#250]
After the SKU model is complete, we will need basic CRUD for managing the SKUs. This includes both routes and simple forms for adding, editing and removing skus, as well as a view of all SKUs.

**Comment by alxngyn** [comment]
1. View
 - [ ] Tests, 1
 - [ ] Code, 3
2. DELETE
 - [ ] Tests, 1
 - [ ] Code, 3
3. ADD/EDIT
 - [ ] Tests, 3
 - [ ] Code, 5
