### ISSUE TITLE
Bundle install and Gemfile issues

### ISSUE THREAD

**Issue by alxngyn** [osuosl/iam#53]
Just wanted to improve the workflow a bit more:

Every time I run the docker container for the first time :   
* I get this error when I `rake spec`. I'm not sure how to fix this one as bundle install is ran during the build process of docker
```
[root@1cb0517f3f0e code]# rake spec
Could not find parser-2.3.0.7 in any of the sources
Run `bundle install` to install missing gems.
```

* Also, I know @matthewrsj and maybe others get this error because of two versions of the redis gem installed. This should be an easy fix with the Gemfile
```
[root@1cb0517f3f0e code]# ruby scheduler.rb 
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/runtime.rb:35:in `block in setup': You have already activated redis 3.3.0, but your Gemfile requires redis 3.2.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

**Comment by alxngyn** [comment]
For some reason, I don't think removing the Gemfile fixed it long term. 

**Is anyone getting this when they work on IAM?** This might be specific to me

```
pvector@green:~/Documents/github/iam$ sudo docker-compose run dev bash
Starting iam_redis_1
Starting iam_postgres_1
[root@0f5c079b2e59 code]# rake spec
Could not find rufus-scheduler-3.2.0 in any of the sources
Run `bundle install` to install missing gems.
```
```
bundle install
... does its thing ...
```
```
[root@0f5c079b2e59 code]# ruby scheduler.rb 
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/runtime.rb:35:in `block in setup': You have already activated sequel 4.34.0, but your Gemfile requires sequel 4.33.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```
is fixed by :
```
[root@0f5c079b2e59 code]# gem uninstall sequel

Select gem to uninstall:
 1. sequel-4.33.0
 2. sequel-4.34.0
 3. All versions
> 2
Successfully uninstalled sequel-4.34.0
```

This is similar to what we had before but with different gems.

**Comment by ElijahCaine** [comment]
@alxngyn have you tried running `docker-compose build --no-cache`? That might be a thing we need to do once or twice a week, or whenever we add a dependency (which did happen recently).

**Comment by alxngyn** [comment]
`docker-compose build --no-cache` did it for me.  Looks like it's just going to be a dev workflow woe until something cooler comes along

**Comment by ElijahCaine** [comment]
@alxngyn this feels pretty resolved. Think we can close this?

**Comment by matthewrsj** [comment]
*I* haven't run in to any more issues
