### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/iam#55]
Probably Apache v2, that's the norm for our projects.

**Comment by matthewrsj** [comment]
+1 for Apache v2

**Comment by alxngyn** [comment]
Are there Docs on why OSL uses Apachev2 instead of MIT, gnu, etc?

**Comment by matthewrsj** [comment]
@alxngyn I looked, but haven't found them. I have asked this question before and @Kennric gave a very good answer, I just don't remember what it was...

**Comment by ElijahCaine** [comment]
@alxngyn an non fulfilling  answer is that we use Apache v2 because we use Apache v2. Standardizing tends to be good. I personally like that we don't bike-shed about it every project.

**Comment by matthewrsj** [comment]
+1 for Apache because of

> I personally like that we don't bike-shed about it every project.

**Comment by matthewrsj** [comment]
Oh no! We're bike-shedding *right now*.
