### ISSUE TITLE
Polish DiskSize Plugin For Replication

### ISSUE THREAD

**Issue by matthewrsj** [osuosl/iam#58]
We should polish the DiskSize plugin so that everyone is satisfied with code/structure. This will be our standard for writing all the other plugins.

**Comment by alxngyn** [comment]
I thought we we're planning to do a VCPU plugin to contrast differences and similarities.
Then do polishing (like plugin base class, spec structure, etc)

**Comment by matthewrsj** [comment]
Yes, but we should be contrasting differences and similarities against a polished plugin. Also, we will replicate whatever we can.

**Comment by matthewrsj** [comment]
The spec tests should be pretty similar, for instance.

**Comment by alxngyn** [comment]
resolved #56
