### ISSUE TITLE
Containerize it!

### ISSUE THREAD

**Issue by mathuin** [osuosl/iam#6]
This project should be broken down into containers which are orchestrated by Docker Compose.

Examples:
https://github.com/convox-examples/sinatra/blob/master/docker-compose.yml
https://github.com/bigcommerce/hello-world-app-ruby-sinatra/blob/master/docker-compose.yml
https://github.com/realpython/flask-sinatra-martini/blob/master/ruby/docker-compose.yml

**Comment by ElijahCaine** [comment]
I'm already working on this on the `elijah/docker-dev-env` branch. It's gonna use all the cool things like docker-compose and linked containers. PR pending as we upgrade docker on the workstations.

**Comment by alxngyn** [comment]
#16 Merged
