### ISSUE TITLE
Move routes out of app.rb

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/iam#69]
`app.rb` is going to get huge if we keep adding routes to it. We can move the routes to their own directory, it's pretty well outlined in the [sinatra docs](http://www.sinatrarb.com/intro.html#Sinatra::Base%20-%20Middleware,%20Libraries,%20and%20Modular%20Apps).

Thoughts?

**Comment by matthewrsj** [comment]
I agree. Adding projects views already starts to make it large.

**Comment by matthewrsj** [comment]
I was going to try to emulate this in #64, but it looks like you are introducing some necessary structure in #70. I'll leave #64 as-is for now and you can move the code out in #70.

**Comment by alxngyn** [comment]
PR merged
Good work @ElijahCaine
