### ISSUE TITLE
Logging implementation

### ISSUE THREAD

**Issue by alxngyn** [osuosl/iam#77]
Nice to have feature,
* research which logging gem would be best
* create a config where users can dictate where the log file goes

**Comment by matthewrsj** [comment]
A couple options I've found:

* https://github.com/TwP/logging
* https://github.com/colbygk/log4r

They are pretty similar, but the first option seems to require slightly less work:

From `logging` documentation:
```ruby
require 'logging'

logger = Logging.logger(STDOUT)
logger.level = :warn

logger.debug "this debug message will not be output by the logger"
logger.warn "this is your last warning"
```

From `log4r` documentation:
```ruby
require 'log4r'
include Log4r

# create a logger named 'mylog' that logs to stdout
mylog = Logger.new 'mylog'
mylog.outputters = Outputter.stdout

# Now we can log.
def do_log(log)
  log.debug "This is a message with level DEBUG"
  log.info "This is a message with level INFO"
  log.warn "This is a message with level WARN"
  log.error "This is a message with level ERROR"
  log.fatal "This is a message with level FATAL"
end
do_log(mylog)
```

**Comment by alxngyn** [comment]
I vote for logging and how it is easy to setup and use. The setup/use is also similar to everything else we do.

**Comment by ElijahCaine** [comment]
As long as we can specify in a configure file where we are logging to I think both are adequate. If they're about even I'd go with the one that requires fewer dependencies or the one that is more heavily maintained.

**Comment by hsolorza** [comment]
Logging added #146 and #145
