### ISSUE TITLE
Sinatra framework setup

### ISSUE THREAD

**Issue by mathuin** [osuosl/iam#8]

**Comment by Kennric** [comment]
Base sinatra app is in kennric/examples

@matthewrsj or @ElijahCaine - close this issue when models.rb, app.rb, rakefile, gemfile are merged into develop

**Comment by alxngyn** [comment]
Example framework coming in with PR #26

**Comment by matthewrsj** [comment]
@Kennric can this be closed?

**Comment by Kennric** [comment]
Closing, this is taken care of.
