### ISSUE TITLE
Project CRUD

### ISSUE THREAD

**Issue by alxngyn** [osuosl/iam#80]
Project CRUD needs to be created 
* similar to clients CRUD

**Comment by alxngyn** [comment]
update: I'm doing some partial work on this issue because i'm working on the demo/report-view stuff

**Comment by ElijahCaine** [comment]
@alxngyn Based on the code in `views/projects.rb` it looks like this is already complete.

**Comment by alxngyn** [comment]
What do you mean?
My understanding is that we needed a UI to create, read, update, and delete.  We can view the list of projects but can't update or delete them right now.

**Comment by ElijahCaine** [comment]
The UI and the endpoints for calling those endpoints are separate. Based on the code we have in the repo the endpoints already exist we just haven't created the forms and buttons for calling them. @Kennric might have a different view on things but it's my understanding that the UI and the CRUD are separate issues.

**Comment by alxngyn** [comment]
@ElijahCaine Alrighty. I can separate the view segment into another issue

**Comment by ElijahCaine** [comment]
@alxngyn @Kennric This looks like it's already been merged into https://github.com/osuosl/iam/blob/develop/routes/projects.rb  is that right and should we close this?
