### ISSUE TITLE
Cookbook for production instance

### ISSUE THREAD

**Issue by alxngyn** [osuosl/iam#83]
As we discussed in the sprint meeting, we just need the scheduler be running to collect data while we work on the app. 
- cookbook for the app
- cookbook for postgres(?)
- we probably want backups on the data at some interval

**Comment by ElijahCaine** [comment]
Just to clarify, this cookbook will live in a separate repository on https://github.com/osuosl-cookbooks .

**Comment by ElijahCaine** [comment]
@Kennric Since we are going to use Ansible for deploying, and that will live on a different repository, should this issue still be open?

**Comment by Kennric** [comment]
resolved with ansible deploy and app server cookbooks
