### ISSUE TITLE
Explore using file-based cache instead of Redis

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/iam#94]
A question was brought up when I was talking with some of the systems folks here at the OSL that I didn't have a great answer to: *"Why don't you just use a file for your cache?"*

As I see it we can store files in memory, load them into the application easily with `JSON.parse()` and write our cache data structure to a file with `JSON.dumps()`.

With that said, let's have a discussion about the pros/cons of using a file instead of Redis. I'll get started:

**Pro:** Less dependencies

**Cons:** Slower (?)

@osuosl/devs @Kennric

**Comment by matthewrsj** [comment]
Well, as we just discussed, we are not utilizing our KV store as an actual KV store, since our workflow looks like this:

1. query api for buld data, store in redis as objects
2. pull **all** data out of redis to store in DB

Nothing KV about that. 

Idea: In the collect method initialize function, read in the file as a ruby hash. Each collector method then updates the relevant part of the data. A deconstructor method then stores the hash back in the file.

+1 for using a file.

**Comment by ElijahCaine** [comment]
**Summary of meatspace discussion:**
The idea of Redis was nice before we had the `collectors / store` separation and the design constructs that grew around that. We ended up not really needing the Key:Value store methods as much as we expected.

As it is we basically just use Redis to dump data into and out of.

The things we use Redis for can be achieved with a file fairly painlessly by storing our cache in an `.iam-cache` directory and separate files for each resource type (`node` `database` and `ftp` for instance).

**Comment by mathuin** [comment]
My first concern with a file-based cache is scalability.

If there are multiple instances running this code, each instance will have its own file-based cache.  Will they step on each other at all?  Are there any assumptions in the codebase that there will be only one instance running at any given time?

Other than that, it sounds like a great idea.

**Comment by ElijahCaine** [comment]
@mathuin Thanks for bringing up some good points @mathuin.

As far as the file-based cache scaling with multiple instances of the code running, I think this is a valid question. As it stands in PR #97 it's only practical to run this application as one instance on a single machine. There are two ways to look at the scaling problem:
**A.** We shouldn't worry about scaling out until it becomes a problem (the file cache solution)
**B.** We should preemptively optimize the heck out of this app (the Redis cache solution)

In my experience we haven't *ever* needed to *actually* worry about large scaling problems. The advantages of reducing our dependency count outweigh the hypothetical potential advantages we get down the line by using a robust network-based/in-memory caching system like Redis.

**Note:**
I have implemented an abstracted `Cache` class which has the `get`, `set`, `del`, and `write` methods. Somewhere down the line we could pretty painlessly re-work it to use Redis on the back-end without touching too much of the code that uses the cache. This was something I wanted to do earlier but didn't have an excuse to do it.
